### ISSUE TITLE
Deblurring and Interpolation

### ISSUE THREAD

**Issue by chensong1995** [yunfanLu/Awesome-Events-Deep-Learning#2]
Thank you for writing this fantastic survey! I learned a lot from reading your paper.

I have a small suggestion. I feel like the difference between frame interpolation and deblurring is not explained very clearly on pages 7-8 (Sections 3.3-3.4). It appears to me that the main difference is the input and output.

Frame interpolation methods take two or more conventional frames and the events between them as input. Representative frame interpolation methods include Timelens and Timelens++. Frame interpolation methods typically output a video.

Deblurring methods take one single conventional frame and its associated events as input. Deblurring methods can be further divided into two categories based on the output format, including image-to-image deblurring methods (e.g. EFNet), and image-to-video deblurring methods (e.g. EDI, eSL-Net, E-CIR).

Because the conventional frame input in frame interpolation methods can also be blurry, several works (e.g. [86], [88]) borrow experience from image-to-video deblurring methods to jointly tackle the interpolation and deblurring tasks. Alternatively, they can be referred to as video-to-video deblurring methods.

Once again, thank you very much for this wonderful work!

**Comment by yunfanLu** [comment]
Thank you for your suggestion. We will update this part in the next update of the paper. Thanks again for your suggestion.
